### ISSUE TITLE
TypeError: expected Tensor as element 0 in argument 0, but got NoneType

### ISSUE THREAD

**Issue by TanZheling** [GeorgeCazenavette/glad#1]
Hi, thank you for the open-source code. However, when run the command:
` python distill_dc.py --dataset=CIFAR10 --layer=16 --ipc=1 --eval_it 1 --space wp`
there is an error:
`Traceback (most recent call last):
  File "glad/distill_dc.py", line 236, in <module>
    main(args)
  File "glad/distill_dc.py", line 185, in main
    gan_backward(latents=latents, f_latents=f_latents, image_syn=image_syn, G=G, args=args)
  File "glad/glad_utils.py", line 435, in gan_backward
    latents.grad = torch.cat(latents_grad_list)
TypeError: expected Tensor as element 0 in argument 0, but got NoneType`

**Comment by GeorgeCazenavette** [comment]
Hi! I'm not at a computer at the moment, but does the same issue occur if you use a smaller layer number? 

I'm thinking that the CIFAR GAN might not have 16 layers, leading to the error. We used layer 2 in the paper, for example.

**Comment by TanZheling** [comment]
Thanks, I think now it works.

**Comment by TanZheling** [comment]
Hi, after changing the layer to 2, it did work for first several trials (all runs successfully complete), then a new error occured in the following trials:
 
`Traceback (most recent call last):`
  `File "glad/distill_dc.py", line 236, in <module>`
    `main(args)`
  `File "glad/distill_dc.py", line 72, in main`
    `latents, f_latents, label_syn = prepare_latents(channel=channel, num_classes=num_classes, im_size=im_size, zdim=zdim, G=G, class_map_inv=class_map_inv, get_images=get_images, args=args)`
  `File "glad/glad_utils.py", line 75, in prepare_latents`
    `latents = G.mapping(zs, G_labels)`
  `File "lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl`
    `return forward_call(*input, **kwargs)`
  `File "lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward`
  `  outputs = self.parallel_apply(replicas, inputs, kwargs)`
`  File "lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 181, in `parallel_apply
    `return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])`
  `File "lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in `parallel_apply
  `  output.reraise()`
  `File "lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise`
   ` raise exception`
`AssertionError: Caught AssertionError in replica 0 on device 0.`
`Original Traceback (most recent call last):`
  `File "lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker`
    `output = module(*input, **kwargs)`
`  File "lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl`
    `return forward_call(*input, **kwargs)`
 ` File "<string>", line 169, in forward`
  `File "glad/stylegan_xl/torch_utils/misc.py", line 95, in assert_shape`
    `raise AssertionError(f'Wrong size for dimension {idx}: got {size}, expected {ref_size}')`
`AssertionError: Wrong size for dimension 1: got 10, expected 1000`

Do you know the reason why this error occurs? Thanks a lot!

**Comment by GeorgeCazenavette** [comment]
Sorry about this, some of the code must have gotten messed up when we were cleaning it up for release.

The issue here is that the Generator that's been loaded expects a 1000-dim class vector, but it's receiving a 10-sim class vector.

Could you give me more details about the command you ran so I can fix it?

Thanks!

**Comment by TanZheling** [comment]
> Sorry about this, some of the code must have gotten messed up when we were cleaning it up for release.
> 
> The issue here is that the Generator that's been loaded expects a 1000-dim class vector, but it's receiving a 10-sim class vector.
> 
> Could you give me more details about the command you ran so I can fix it?
> 
> Thanks!

Thanks, this problem is solved! However, I can't quite replicate the CIFAR10 result. It seems like in your paper, for DC method, for a trained GAN, the result of ipc=1, layer=2 is 27.6. However, I only get 19.47. I didn't change other hyperparameters. Could you give me more details about the parameter settings so I can better understand if I made some mistakes? Thank you again!

**Comment by GeorgeCazenavette** [comment]
Make sure --eval_mode=CIFAR and --depth=3

If that doesn't work, I can go find the logs in the morning :)

**Comment by TanZheling** [comment]
Now it's only 0.1203 on Conv (model=Conv3), my hyperparams are as following:
`'dataset': 'CIFAR10', 'model': 'ConvNet', 'ipc': 1, 'eval_mode': 'CIFAR', 'num_eval': 5, 'eval_it': 100, 'save_it': None, 'epoch_eval_train': 1000, 'Iteration': 1000, 'mom_img': 0.5, 'batch_real': 256, 'batch_train': 256, 'batch_test': 128, 'pix_init': 'noise', 'dsa': True, 'dsa_strategy': 'color_crop_cutout_flip_scale_rotate', 'data_path': 'data', 'save_path': 'result/dc/20230607-004603-CIFAR101ConvNet2', 'space': 'wp', 'res': 128, 'layer': 2, 'avg_w': False, 'eval_all': False, 'min_it': False, 'no_aug': False, 'force_save': False, 'sg_batch': 10, 'rand_f': False, 'logdir': './logged_files', 'wait_eval': False, 'idc_factor': 1, 'rand_gan_un': False, 'rand_gan_con': False, 'learn_g': False, 'width': 128, 'depth': 3, 'special_gan': None, 'train_ann': None, 'test_ann': None, 'method': 'DC', 'lr_img': 1, 'lr_w': 0.001, 'lr_g': 0.0001, 'lr_net': 0.01, 'inner_loop': 1, 'outer_loop': 1, 'dis_metric': 'ours', 'device': 'cuda', 'dsa_param': <utils.ParamDiffAug object at 0x7f2eeba4ecd0>, 'distributed': False`
Could you please help me check these hyperparameters?

**Comment by GeorgeCazenavette** [comment]
Could you set avg_w=True?

**Comment by TanZheling** [comment]
Now it's 0.16098 on Conv, my hyperparams are:
`'dataset': 'CIFAR10', 'model': 'ConvNet', 'ipc': 1, 'eval_mode': 'CIFAR', 'num_eval': 5, 'eval_it': 100, 'save_it': None, 'epoch_eval_train': 1000, 'Iteration': 1000, 'mom_img': 0.5, 'batch_real': 256, 'batch_train': 256, 'batch_test': 128, 'pix_init': 'noise', 'dsa': True, 'dsa_strategy': 'color_crop_cutout_flip_scale_rotate', 'data_path': 'data', 'save_path': 'result/dc/20230607-221847-CIFAR101ConvNet2', 'space': 'wp', 'res': 128, 'layer': 2, 'avg_w': True, 'eval_all': False, 'min_it': False, 'no_aug': False, 'force_save': False, 'sg_batch': 10, 'rand_f': False, 'logdir': './logged_files', 'wait_eval': False, 'idc_factor': 1, 'rand_gan_un': False, 'rand_gan_con': False, 'learn_g': False, 'width': 128, 'depth': 3, 'special_gan': None, 'train_ann': None, 'test_ann': None, 'method': 'DC', 'lr_img': 1, 'lr_w': 0.001, 'lr_g': 0.0001, 'lr_net': 0.01, 'inner_loop': 1, 'outer_loop': 1, 'dis_metric': 'ours', 'device': 'cuda', 'dsa_param': <utils.ParamDiffAug object at 0x7f3d0c804d30>, 'distributed': False`
Were there anything I didn't notice?

**Comment by TanZheling** [comment]
Thanks, now the results are similar to your paper! Thanks for your help!
